AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:

  myHostedZoneName:
    Description: 'The name of the domain (hosted zone).'
    Type: List<AWS::Route53::HostedZone::Id>

  
  
Metadata:
  
Mappings:
  
Conditions:
  
Resources:

  myHostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub "$(myHostedZoneName) public DNS zone"
      Name: !Ref myHostedZoneName #required
      VPCs:
        - VPC eklenecek

  myS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccelerateConfiguration:
        AccelerateConfiguration
      AccessControl: String
      AnalyticsConfigurations:
        - AnalyticsConfiguration
      BucketName: !Sub www.$(myHostedZoneName) #test et
      CorsConfiguration:
        CorsConfiguration
      InventoryConfigurations:
        - InventoryConfiguration
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
        




  
Transform:
  
Outputs: